#!/bin/bash

if [ "$1" = "" ]
then
  echo "Usage: $0 <problem to be created>"
  exit
fi

cd problems
mkdir p$1
cd p$1
touch p$1.cpp p$1.py
printf "/*\nproject euler problem $1\n*/\n#include <iostream>\n" >> p$1.cpp
printf "\"\"\"\nproject euler problem $1\n\"\"\"\n" >> p$1.py
open -a /Applications/Atom.app/ p$1.cpp p$1.py
cd ../../
