#!/bin/bash

if [ "$1" = "" ]
then
  echo "Usage: $0 <problem to run>"
  exit
fi

g++ problems/p$1/p$1.cpp
printf "C++\n-----------\n"
time ./a.out
printf "\npython\n-----------\n"
time python problems/p$1/p$1.py
rm a.out
